import arcade

# SCREEN AREAS
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
DESCRIPTION_WIDTH = 600
CHARACTER_WIDTH = 200
DESCRIPTION_HEIGHT = SCREEN_HEIGHT
CHARACTER_HEIGHT = SCREEN_HEIGHT

# COLORS
BACKGROUND_COLOR = arcade.color.BLACK
TEXT_COLOR = arcade.color.WHITE
TEXT_HOVER_COLOR = arcade.color.REDWOOD

# GAME
START_SCENE_ID = 0
