import arcade

# SCREEN
GAME_TITLE = "Choose Your Adventure"
SCREEN_WIDTH = 1280 #800
SCREEN_HEIGHT = 720 #600
DESCRIPTION_WIDTH = 980
CHARACTER_WIDTH = 300
DESCRIPTION_HEIGHT = SCREEN_HEIGHT
CHARACTER_HEIGHT = SCREEN_HEIGHT
CHARACTER_MARGIN = 20
TOP_MARGIN = 50
SECOND_COLUMN_X = 350

# COLORS
BACKGROUND_COLOR = arcade.color.BLACK
TEXT_COLOR = arcade.color.WHITE
TEXT_HOVER_COLOR = arcade.color.GOLD
ACTION_TEXT_COLOR = arcade.color.CELESTE

# FONT
FONT_PATH = "fonts/FiraCode-SemiBold.ttf"
FONT_NAME = "Fira Code SemiBold"
FONT_SIZE = 12

# GAME
START_STATE = 0
START_SCENE_ID = 0
